// File generated by FlutterFire CLI - Mocked for Prototype
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZhVtqbBUhzWPQuLZMaiLGtJktMxhNOs',
    appId: '1:261612415694:web:386fbe49ac9a0eb399be9f',
    messagingSenderId: '261612415694',
    projectId: 'sargon-25f65',
    authDomain: 'sargon-25f65.firebaseapp.com',
    databaseURL: 'https://sargon-25f65-default-rtdb.firebaseio.com',
    storageBucket: 'sargon-25f65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5z8O-utbtV3rp7zpb2sb8BqbEFjL7V0',
    appId: '1:261612415694:android:5d0477876099230399be9f',
    messagingSenderId: '261612415694',
    projectId: 'sargon-25f65',
    databaseURL: 'https://sargon-25f65-default-rtdb.firebaseio.com',
    storageBucket: 'sargon-25f65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-sender-id',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosClientId: 'mock-client-id',
    iosBundleId: 'com.hotelmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'mock-api-key',
    appId: 'mock-app-id',
    messagingSenderId: 'mock-sender-id',
    projectId: 'mock-project-id',
    storageBucket: 'mock-project-id.appspot.com',
    iosClientId: 'mock-client-id',
    iosBundleId: 'com.hotelmanager',
  );
}