import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hotel_manager/core/navigation/app_router.dart';
import 'package:hotel_manager/features/attendance/logic/attendance_cubit.dart';
import 'package:hotel_manager/features/auth/logic/auth_cubit.dart';
import 'package:hotel_manager/features/checklists/logic/checklist_cubit.dart';
import 'package:hotel_manager/features/incidents/logic/incident_cubit.dart';
import 'package:hotel_manager/features/inventory/goods_receipt/logic/goods_receipt_cubit.dart';
import 'package:hotel_manager/features/inventory/purchase_orders/logic/purchase_order_cubit.dart';
import 'package:hotel_manager/features/inventory/stock/logic/inventory_cubit.dart';
import 'package:hotel_manager/features/inventory/vendors/logic/vendor_cubit.dart';
import 'package:hotel_manager/features/orders/logic/order_cubit.dart';
import 'package:hotel_manager/features/performance/logic/performance_cubit.dart';
import 'package:hotel_manager/features/rooms/logic/room_cubit.dart';
import 'package:hotel_manager/features/staff_mgmt/logic/user_cubit.dart';

// This will be generated by FlutterFire CLI, but we'll mock it for now or comment it out until setup.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  final checklistCubit = ChecklistCubit();
  final inventoryCubit = InventoryCubit();
  final purchaseOrderCubit = PurchaseOrderCubit();
  final vendorCubit = VendorCubit();

  runApp(
    MultiBlocProvider(
      providers: [
        BlocProvider<AuthCubit>(create: (context) => AuthCubit()),
        BlocProvider<ChecklistCubit>(create: (context) => checklistCubit),
        BlocProvider<UserCubit>(create: (context) => UserCubit()..loadUsers()),
        BlocProvider<OrderCubit>(create: (context) => OrderCubit()),
        BlocProvider<InventoryCubit>(create: (context) => inventoryCubit),
        BlocProvider<PurchaseOrderCubit>(
          create: (context) => purchaseOrderCubit,
        ),
        BlocProvider<VendorCubit>(create: (context) => vendorCubit),
        BlocProvider<GoodsReceiptCubit>(
          create: (context) => GoodsReceiptCubit(
            inventoryCubit: inventoryCubit,
            purchaseOrderCubit: purchaseOrderCubit,
          ),
        ),
        BlocProvider<AttendanceCubit>(create: (context) => AttendanceCubit()),
        BlocProvider<IncidentCubit>(create: (context) => IncidentCubit()),
        BlocProvider<PerformanceCubit>(create: (context) => PerformanceCubit()),
        BlocProvider<RoomCubit>(
          create: (context) => RoomCubit(checklistCubit: checklistCubit),
        ),
      ],
      child: const HotelManagerApp(),
    ),
  );
}

class HotelManagerApp extends StatelessWidget {
  const HotelManagerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Hotel Manager',
      debugShowCheckedModeBanner: false, // Remove debug banner
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1A237E),
        ), // Deep Blue
        useMaterial3: true,
        textTheme: GoogleFonts.interTextTheme(),
      ),
      routerConfig: createRouter(),
    );
  }
}
